### ISSUE TITLE
'PHP Fatal error' every 15 mins all day

### ISSUE THREAD

**Issue by Simon921** [jsdelivr/plugin-wordpress#37]
my wp version is 5.4.2, php version 7.0.27
and below is the error log:

> [Thu Jun 11 18:16:39.038137 2020] [:error] [pid 173831:tid 140107535165184] [client x.x.x.x:0] PHP Fatal error:  Uncaught Error: Call to undefined function WP_Filesystem() in /XXX.COM/wp-content/plugins/plugin-wordpress-master/classes/class-jsdelivrcdn.php:217, referer: https://xxx.com/wp-cron.php?doing_wp_cron=1591870598.3761730194091796875000
[Thu Jun 11 18:16:39.038203 2020] [:error] [pid 173831:tid 140107535165184] [client x.x.x.x:0] Stack trace:, referer: https://xxx.com/wp-cron.php?doing_wp_cron=1591870598.3761730194091796875000
[Thu Jun 11 18:16:39.038362 2020] [:error] [pid 173831:tid 140107535165184] [client x.x.x.x:0] #0 /XXX.COM/wp-content/plugins/plugin-wordpress-master/classes/class-jsdelivrcdn.php(586): JsDelivrCdn::get_jsdelivr_source_url(Array), referer: https://xxx.com/wp-cron.php?doing_wp_cron=1591870598.3761730194091796875000
[Thu Jun 11 18:16:39.038464 2020] [:error] [pid 173831:tid 140107535165184] [client x.x.x.x:0] #1 /XXX.COM/wp-includes/class-wp-hook.php(287): JsDelivrCdn::analyze(), referer: https://xxx.com/wp-cron.php?doing_wp_cron=1591870598.3761730194091796875000
[Thu Jun 11 18:16:39.038574 2020] [:error] [pid 173831:tid 140107535165184] [client x.x.x.x:0] #2 /XXX.COM/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array), referer: https://xxx.com/wp-cron.php?doing_wp_cron=1591870598.3761730194091796875000
[Thu Jun 11 18:16:39.038672 2020] [:error] [pid 173831:tid 140107535165184] [client x.x.x.x:0] #3 /XXX.COM/wp-includes/plugin.php(544): WP_Hook->do_action(Array), referer: https://xxx.com/wp-cron.php?doing_wp_cron=1591870598.3761730194091796875000
[Thu Jun 11 18:16:39.038791 2020] [:error] [pid 173831:tid 140107535165184] [client x.x.x.x:0] #4 /XXX.COM/wp-cron.php(138): do_action_ref_array('jsdelivr_analyz...', Array), referer: https://xxx.com/wp-cron.php?doing_wp_cron=1591870598.3761730194091796875000
[Thu Jun 11 18:16:39.038809 2020] [:error] [pid 173831:tid 140107535165184] [client x.x.x.x:0] #5 {main}, referer: https://xxx.com/wp-cron.php?doing_wp_cron=1591870598.3761730194091796875000
[Thu Jun 11 18:16:39.038938 2020] [:error] [pid 173831:tid 140107535165184] [client x.x.x.x:0]   thrown in /XXX.COM/wp-content/plugins/plugin-wordpress-master/classes/class-jsdelivrcdn.php on line 217, referer: https://xxx.com/wp-cron.php?doing_wp_cron=1591870598.3761730194091796875000

Thanks for your great plugin~

**Comment by Simon921** [comment]
fyi, some posts said such issue could be solved by inserting
 `require_once(ABSPATH . 'wp-admin/includes/file.php');`
into the beginning of the code.
I tried that and it worked.
